### ISSUE TITLE
Criar a Navbar (Barra de Navegação)

### ISSUE THREAD

**Issue by eduardoalen** [UDFProjLingProg/Signacle#4]
## Criar Navbar com os seguintes itens: 
- Logo da UDF
- Botão "Início"
- Botão "Sobre"
- Botão “Equipe”
- Botão “Signacle”
- Botão “Contato”
- Botão “Login”

### Como pode ser visualizado na imagem abaixo e no Figma.
![Image](https://github.com/user-attachments/assets/28fe363a-3f04-4653-890c-c2b063607d3a)
Link Figma: https://www.figma.com/design/jKghfrsuhdincC64MQQGPc/Untitled?node-id=0-1&node-type=canvas&t=zvNFhArhqbwWAr20-0

**Comment by JoaoPedro-git** [comment]
Realizado por: João Pedro Santos Cruz 27674304
![image](https://github.com/user-attachments/assets/372a268c-2e63-44b4-b68b-de3547823d53)


Atividade(s) realizada(s):
Logo da UDF
Botão "Início"
Botão "Sobre"
Botão “Equipe”
Botão “Signacle”
Botão “Contato”
Botão “Login”
